#!/usr/bin/env bash
# This script installs and configures HAproxy

# Install HAproxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAproxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server web-01 18.204.5.218:80 check
   server web-02 100.26.218.215:80 check
EOL

# Restart HAproxy to apply changes
sudo service haproxy restart
