#!/usr/bin/env bash
# installing & Configuring HAProxy and load_balancer

# update the package list 
sudo apt-get -y update

# install required packages
sudo apt-get -y install software-properties-common

# Add HAProxy repository and install HAProxy 2.0
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

# HAProxy configuration
load_balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 100.25.190.203:80 check
    server web-02 54.175.134.168:80 check
"
# Add your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$load_balancer" >> /etc/haproxy/haproxy.cfg

# Start the HAProxy service
sudo service haproxy start
