#!/usr/bin/env bash
# Script to ensure nginx listens on port 80

# remove default nginx file config
rm /etc/nginx/sites-enabled/default
# nginx config  to listen on port 80 for ll IPV4 Ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# nginx start
service nginx restart
