#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iteration
phrase="Best School"
i=0
while ((i < 10))
do 
	if ((i==3))
  	then 
		echo "bad luck"
	elif ((i==7))
	then 
		echo "good luck"
	else
		echo "$phrase"
	fi
	((i = i + 1))
done
