#!/bin/bash
counter=1
whiles [$counter -le 10]
do 
	if [$counter -eq 4]
  	then 
		echo "Bad luck"
	elif [$counter -eq 8]
	then 
		echo "Good luck"
	else
		ehco "Best School"
	fi
	counter =$((counter+1))
done
