#!/usr/bin/env bash
# update
sudo apt-get update

# ufw installation
sudo apt-get install ufw

# disable policies
sudo ufw default deny incoming

# 3-way port entry
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# verbose output
sudo ufw status verbose

# enable ufw
sudo ufw enable

# status check
sudo ufw status
