#!/usr/bin/env bash
# Setup nginx web server

sudo apt-get update
sudo apt-get -y install nginx

# Allow nginx access through firewall
sudo ufw allow 'Nginx HTTP'

# Overwrite default html
sudo bash -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"

sudo service nginx start

# 301 redirection
rdrct='server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sudo sed -i "s|server_name\s*_;|$rdrct|" /etc/nginx/sites-available/default

# Add custom response header
cst_hdr="listen [::]:80 default_server;\n\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "s|listen \[::\]:80 default_server;|$cst_hdr|" /etc/nginx/sites-available/default

# Write custom 404 error page
sudo bash -c "echo 'Ceci n'est pas une page' > /usr/share/nginx/html/custom_404.html"

# Enable custom 404
err_pg="listen [::]:80 default_server;\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "s|listen \[::\]:80 default_server;|$err_pg|" /etc/nginx/sites-available/default

# Enable default conf
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
